
export const GET_PERSONAL_MANTENIMIENTO = "GET_PERSONAL_MANTENIMIENTO";
export const GET_PERSONAL_MANTENIMIENTO_BY_ID = "GET_PERSONAL_MANTENIMIENTO_BY_ID";
export const CREAR_PERSONAL_MANTENIMIENTO = "CREAR_PERSONAL_MANTENIMIENTO";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";