export const USUARIOS_ACTIONS = {
    LISTAR: 'LISTAR_USUARIOS',
    OBTENER: 'OBTENER_USUARIO',
    REGISTRAR: 'REGISTRAR_USUARIO',
    ACTUALIZAR: 'ACTUALIZAR_USUARIO',
    ELIMINAR: 'ELIMINAR_USUARIO',
    REACTIVAR: 'REACTIVAR_USUARIO',
    TIPOS_USUARIO: 'OBTENER_TIPOS_USUARIO',
    LOADING: 'USUARIOS_LOADING',
    SAVING: 'USUARIOS_SAVING',
    CLEAR_ERROR: 'USUARIOS_CLEAR_ERROR',
    ERROR: 'USUARIOS_ERROR'
};
