export const PERFIL_ACTIONS = {
    LOADING: "PERFIL_LOADING",
    SAVING: "PERFIL_SAVING",
    OBTENER: "PERFIL_OBTENER",
    ACTUALIZAR: "PERFIL_ACTUALIZAR",
    ERROR: "PERFIL_ERROR",
    CLEAR_ERROR: "PERFIL_CLEAR_ERROR",
};