export const ESTADISTICAS_ACTIONS = {
    LOADING: "ESTADISTICAS_LOADING",
    GET_INCIDENTES: "ESTADISTICAS_GET_INCIDENTES",
    GET_PAGOS: "ESTADISTICAS_GET_PAGOS",
    GET_SERVICIOS: "ESTADISTICAS_GET_SERVICIOS",
    EXPORTAR_PDF: "ESTADISTICAS_EXPORTAR_PDF",
    ERROR: "ESTADISTICAS_ERROR",
    CLEAR_ERROR: "ESTADISTICAS_CLEAR_ERROR",
};