// context/Servicios/ActionsTypes.js

// Estados generales
export const SERVICIOS_SET_LOADING = "SERVICIOS_SET_LOADING";
export const SERVICIOS_SET_ERROR = "SERVICIOS_SET_ERROR";

// Tipos de servicio
export const SERVICIOS_SET_TIPOS = "SERVICIOS_SET_TIPOS";

// Catálogo de proveedores de servicio
export const SERVICIOS_SET_CATALOGO = "SERVICIOS_SET_CATALOGO";
export const SERVICIOS_ADD_CATALOGO = "SERVICIOS_ADD_CATALOGO";
export const SERVICIOS_UPDATE_CATALOGO = "SERVICIOS_UPDATE_CATALOGO";

// Personal de mantenimiento
export const SERVICIOS_SET_PERSONAL = "SERVICIOS_SET_PERSONAL";
export const SERVICIOS_ADD_PERSONAL = "SERVICIOS_ADD_PERSONAL";

// Solicitudes de servicio
export const SERVICIOS_SET_SOLICITUDES = "SERVICIOS_SET_SOLICITUDES";
export const SERVICIOS_UPDATE_SOLICITUD = "SERVICIOS_UPDATE_SOLICITUD";
export const SERVICIOS_ADD_SOLICITUD = "SERVICIOS_ADD_SOLICITUD";

// Cargos por servicios
export const SERVICIOS_SET_CARGOS_SERVICIOS = "SERVICIOS_SET_CARGOS_SERVICIOS";
export const SERVICIOS_ADD_CARGO_SERVICIO = "SERVICIOS_ADD_CARGO_SERVICIO";

// Cargos de mantenimiento
export const SERVICIOS_SET_CARGOS_MANT = "SERVICIOS_SET_CARGOS_MANT";
export const SERVICIOS_ADD_CARGO_MANT = "SERVICIOS_ADD_CARGO_MANT";
export const SERVICIOS_UPDATE_CARGO_MANT = "SERVICIOS_UPDATE_CARGO_MANT";
