export const GET_REPORTES_REQUEST = "GET_REPORTES_REQUEST";
export const GET_REPORTES_SUCCESS = "GET_REPORTES_SUCCESS";
export const GET_REPORTES_ERROR = "GET_REPORTES_ERROR";

export const GET_REPORTE_REQUEST = "GET_REPORTE_REQUEST";
export const GET_REPORTE_SUCCESS = "GET_REPORTE_SUCCESS";
export const GET_REPORTE_ERROR = "GET_REPORTE_ERROR";

export const GET_REPORTES_USUARIO_SUCCESS = "GET_REPORTES_USUARIO_SUCCESS";

export const GET_TIPOS_REPORTE_SUCCESS = "GET_TIPOS_REPORTE_SUCCESS";

export const CREATE_REPORTE_REQUEST = "CREATE_REPORTE_REQUEST";
export const CREATE_REPORTE_SUCCESS = "CREATE_REPORTE_SUCCESS";
export const CREATE_REPORTE_ERROR = "CREATE_REPORTE_ERROR";

export const MARCAR_VISTO_SUCCESS = "MARCAR_VISTO_SUCCESS";

// NUEVAS ACCIONES PARA AVISOS
export const CREATE_AVISO_REQUEST = "CREATE_AVISO_REQUEST";
export const CREATE_AVISO_SUCCESS = "CREATE_AVISO_SUCCESS";
export const CREATE_AVISO_ERROR = "CREATE_AVISO_ERROR";

export const GET_AVISOS_REQUEST = "GET_AVISOS_REQUEST";
export const GET_AVISOS_SUCCESS = "GET_AVISOS_SUCCESS";
export const GET_AVISOS_ERROR = "GET_AVISOS_ERROR";

export const GET_CATEGORIAS_AVISO_SUCCESS = "GET_CATEGORIAS_AVISO_SUCCESS";

export const CLEAR_ERROR = "CLEAR_ERROR";